################################################################################
# travis.yml
# github.com/sapiderman/seed-go
###############################################################################

language: go

go:
    - master

before_install:
    - go get -v golang.org/x/lint/golint

script:
    - go version
    - go vet ./...
    - make test
    - make build
