
parameters:
    name: ''
    pool: 'ubuntu-latest'
    goVersion: '1.15'
  
    jobs:
        - job: ${{ parameters.name }}
        pool: ${{ parameters.pool }}
        steps:
            - task: GoTool@0
                displayName: 'Use Go ${{ parameters.goVersion }}'
                inputs:
                version: ${{ parameters.goVersion }}
            
            - script: |
                set -e -x
                mkdir -p '$(GOPATH)/bin'
                echo '##vso[task.prependpath]$(GOROOT)/bin'
                echo '##vso[task.prependpath]$(GOPATH)/bin'
                displayName: 'Create Go Workspace'

        steps:
            - task: Go@0
              displayName: 'Build Application Binary'
              inputs:
                command: 'build'
                workingDirectory: '$(System.DefaultWorkingDirectory)'
                arguments: '-o $(Build.BinariesDirectory)/mylabs-go'