name: Github Actions - Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Vet sources
      run: go vet ./...

    - name: Test project
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Build image
      run: go build -v cmd/Main.go

    - name: Build docker
      run: docker build . --file .docker/Dockerfile -t seed-go-img:$(date +%s)
